witmy: &witmy
  docker:
    - image: circleci/node:8.11.3

version: 2
jobs:
  test:
    - run: npm install
    - run: npm run test
  build:
    <<: *witmy
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *witmy
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  test:
    jobs:
      - test
        filters:
          branches:
            ignore:
              - master
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
